-- 009_puesto_config_id.sql -- clave surrogate en reporting.puesto_config.
--
-- El admin de Django no soporta claves primarias compuestas, y esta es justo la tabla que
-- mas gana con el admin: son 31 filas de relevamiento que alguien tiene que cargar a mano.
-- La terna sigue siendo unica, asi que la foreign key contra counters_name y la semantica
-- no cambian.

-- migrate:up

set local lock_timeout = '5s';

alter table reporting.puesto_config drop constraint puesto_config_pk;

alter table reporting.puesto_config
    add column id integer generated by default as identity primary key;

alter table reporting.puesto_config
    add constraint puesto_config_uq unique (ip, tag, version);

-- migrate:down

set local lock_timeout = '5s';

alter table reporting.puesto_config drop constraint puesto_config_uq;
alter table reporting.puesto_config drop column id;
alter table reporting.puesto_config
    add constraint puesto_config_pk primary key (ip, tag, version);
