# Generated by Django 6.1.1 on 2026-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('fila', models.BooleanField(default=True, editable=False, primary_key=True, serialize=False)),
                ('reassert_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poll_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heartbeat_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speed_max_interval_seconds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_segment_extra_s', models.DecimalField(decimal_places=2, max_digits=10)),
                ('objetivo_cabezas_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rampa_segundos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circuito_minutos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margen_jornada_min', models.IntegerField()),
                ('franja_minutos', models.IntegerField()),
                ('est_fae', models.TextField()),
                ('tz', models.TextField(verbose_name='zona horaria')),
                ('monitor_hora_inicio', models.TimeField(verbose_name='el turno arranca a las')),
            ],
            options={
                'verbose_name': 'parámetros del tablero',
                'verbose_name_plural': 'parámetros del tablero',
                'db_table': '"reporting"."parametros"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plc',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP')),
                ('nombre', models.TextField(blank=True, null=True)),
                ('variador', models.BooleanField(default=False, help_text='Reporta la frecuencia y el estado de la noria')),
            ],
            options={
                'verbose_name': 'PLC',
                'verbose_name_plural': 'PLCs',
                'db_table': '"monitoreo_faena"."plcs"',
                'ordering': ['ip'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuestoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP del PLC')),
                ('tag', models.CharField(max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('orden_linea', models.IntegerField(blank=True, help_text='1 es el primer puesto; N, el de tipificación', null=True)),
                ('offset_min', models.DecimalField(blank=True, decimal_places=2, help_text='Sólo si el puesto no cae donde lo pone la interpolación', max_digits=8, null=True, verbose_name='offset manual (min)')),
            ],
            options={
                'verbose_name': 'posición de puesto',
                'verbose_name_plural': 'posiciones de los puestos',
                'db_table': '"reporting"."puesto_config"',
                'ordering': ['orden_linea', 'ip', 'tag'],
                'managed': False,
            },
        ),
    ]
